INSERT INTO categories (id, name)
VALUES
  (1, 'Tech'),
  (2, 'Science'),
  (3, 'Health'),
  (4, 'Travel'),
  (5, 'Food'),
  (6, 'Fashion'),
  (7, 'Fitness'),
  (8, 'Decor'),
  (9, 'Finance'),
  (10, 'Parenting'),
  (11, 'Self-Improve'),
  (12, 'Art'),
  (13, 'Books'),
  (14, 'Entertainment'),
  (15, 'Sports'),
  (16, 'Environment'),
  (17, 'Business'),
  (18, 'Photography'),
  (19, 'Music'),
  (20, 'Lifestyle'),
  (21, 'Gaming'),
  (22, 'Beauty'),
  (23, 'Education'),
  (24, 'Motivation'),
  (25, 'Comedy'),
  (26, 'Politics'),
  (27, 'History'),
  (28, 'Crafts'),
  (29, 'Gardening'),
  (30, 'Pets'),
  (31, 'Relationships'),
  (32, 'Technology'),
  (33, 'Design'),
  (34, 'Movies'),
  (35, 'Cooking'),
  (36, 'Nature'),
  (37, 'Writing'),
  (38, 'Career'),
  (39, 'Fitness'),
  (40, 'Inspiration'),
  (41, 'Spirituality'),
  (42, 'Hobbies'),
  (43, 'Artificial Intelligence'),
  (44, 'Travel Tips'),
  (45, 'Parenting Tips'),
  (46, 'DIY Projects'),
  (47, 'Entrepreneurship'),
  (48, 'Photography Tips');
